version: '3.9'

services:
  mysql:
    container_name: rk25db
    image: mysql:8.0.29
    ports:
      - 3307:3306
    volumes:
      - ./rk25-final-exam-data:/var/lib/mysql
      - ./rk25-final-exam-config-deamond:/etc/mysql/conf.d
    environment:
      - MYSQL_USER=namnp
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rk25finalexam
    networks:
      - app-network

  app:
    container_name: rk25app
    image: npnam0706/rk25-final-exam:v1.0.0
    ports:
      - 8081:8080
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      - mysql
networks:
  app-network:
    name: rk25-final-exam-network